name: FunnyLib
version: '${project.version}'
main: steve6472.standalone.FunnyLibStandalone
api-version: 1.18
depend:
  - Citizens
  - ProtocolLib
  - CrazyAdvancementsAPI
  - Brigit
commands:
  cmds:
    description: Shows all custom commands
    permission-message: No! Bad participant!
  forcenextphase:
    description: Force next phase
    permission-message: No! Bad participant!