name: FunnyLib
version: '${project.version}'
main: steve6472.standalone.FunnyLibStandalone
api-version: 1.18
commands:
  cmds:
    description: Shows all custom commands
    permission-message: No! Bad participant!